name: Via CEP Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate-cep:
    runs-on: ubuntu-latest

    steps:
    # 1. Configurar o ambiente
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Criar ambiente Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    # 2. Rodar script que faz a requisição para o serviço de CEP usando curl
    - name: Requisição ViaCEP
      run: |
        echo "Recebendo dados..."
        curl -s "https://viacep.com.br/ws/03818030/json/" -o response.json

    # 3. Validar a resposta e concluir o processo
    - name: Validar resposta ViaCEP
      run: |
        echo "Validando resposta..."
        if jq '.erro' response.json | grep -q true; then
          echo "CEP não encontrado"
          exit 1
        fi
        echo "CEP encontrado com sucesso"

    # 4. Exibir os dados da consulta de um CEP qualquer
    - name: Exibir os dados da consulta
      run: |
        echo "Endereço:"
        cat response.json | jq

    # 5. Rodar o script app.js
    - name: Instalar dependências
      run: npm install 

    - name: Rodar app.js
      run: |
        echo "Running app.js..."
        OUTPUT=$(node app.js)
        echo "$OUTPUT" > app-output.txt
        echo "::set-output name=output::$OUTPUT"

    # 6. Validar se a cidade é São Paulo
    - name: Validar cidade
      run: |
        CITY=$(grep -o '"localidade":"[^"]*"' app-output.txt | sed 's/"localidade":"//;s/"//')
        echo "City found: $CITY"
        if [ "$CITY" != "São Paulo" ]; then
          echo "Cidade incorreta: A cidade não é São Paulo"
          exit 1
        fi
        echo "Cidade correta: São Paulo"
